- name: create CloudWatch Alarms and enable monitoring
  hosts: all
  become: True
  gather_facts: True
  vars:
     region: "us-west-2"
  tasks:
     - name: Get instance ID
       action: ec2_facts
     - name: CPU Alarm
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "cpu-util{{ec2_id}}"
         metric: "CPUUtilization"
         namespace: "AWS/EC2"
         statistic: Average
         comparison: ">="
         threshold: 8.5
         period: 300
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance cpu usage is greater than 85% for 15 minutes "
         dimensions: { "InstanceId": "{{ec2_id}}"}
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
     - name: Monitoring
         shell: pip install awscli --upgrade --user
         shell: aws ec2 monitor-instances --instance-ids i-0d562e2fe57f177f7 --region 
         
     - name: Status Failed
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "status-failed{{ec2_id}}"
         metric: "StatusCheckFailed"
         namespace: "AWS/EC2"
         statistic: Minimum
         comparison: ">"
         threshold: 0
         period: 60
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance status check fails"
         dimensions: { "InstanceId": "{{ec2_id}}" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     - name: StatusFailedSystem
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "status-failed-system{{ec2_id}}"
         metric: "StatusCheckFailed_System"
         namespace: "AWS/EC2"
         statistic: Minimum
         comparison: ">"
         threshold: 0
         period: 60
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance status check fails"
         dimensions: { "InstanceId": "{{ec2_id}}" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"] 
     
     - name: StatusFailedInstance
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "status-failed-instance{{ec2_id}}"
         metric: "StatusCheckFailed_Instance"
         namespace: "AWS/EC2"
         statistic: Minimum
         comparison: ">"
         threshold: 0
         period: 60
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance status check fails"
         dimensions: { "InstanceId": "{{ec2_id}}" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     - name: MemoryUtilAlarm
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "memory-util{{ec2_id}}"
         metric: "MemoryUtilization"
         namespace: "Windows/Default"
         statistic: Minimum
         comparison: ">"
         threshold: 85
         period: 300
         evaluation_periods: 2
         unit: "Percent"
         description: "Alarm is triggered when the memory is full"
         dimensions: { "InstanceId": "{{ec2_id}}" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     - name: DiskUtilAlarm
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "disk-util{{ec2_id}}"
         metric: "DiskSpaceUtilization"
         namespace: "Windows/Default"
         statistic: Minimum
         comparison: ">"
         threshold: 85
         period: 300
         evaluation_periods: 2
         unit: "Percent"
         description: "Alarm is triggered when the memory is full"
         dimensions: { "InstanceId": "{{ec2_id}}" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     
     
