- name: create CloudWatch Alarms
  hosts: all
  become: True
  gather_facts: False
  tasks:
     - name: CPU Alarm
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "cpu-util"
         metric: "CPUUtilization"
         namespace: "AWS/EC2"
         statistic: Average
         comparison: ">="
         threshold: 8.5
         period: 300
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance cpu usage is greater than 85% for 15 minutes "
         dimensions: {'InstanceId': "i-04c62b676ca15122e" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     - name: Status Failed
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "status-failed"
         metric: "StatusCheckFailed"
         namespace: "AWS/EC2"
         statistic: Minimum
         comparison: ">"
         threshold: 0
         period: 60
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance status check fails"
         dimensions: {'InstanceId': "i-04c62b676ca15122e" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     - name: StatusFailedSystem
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "status-failed-system"
         metric: "StatusCheckFailed_System"
         namespace: "AWS/EC2"
         statistic: Minimum
         comparison: ">"
         threshold: 0
         period: 60
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance status check fails"
         dimensions: {'InstanceId': "i-04c62b676ca15122e" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"] 
     
     - name: StatusFailedInstance
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "status-failed-instance"
         metric: "StatusCheckFailed_Instance"
         namespace: "AWS/EC2"
         statistic: Minimum
         comparison: ">"
         threshold: 0
         period: 60
         evaluation_periods: 3
         unit: "Percent"
         description: "This will alarm when instance status check fails"
         dimensions: {'InstanceId': "i-04c62b676ca15122e" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     - name: MemoryUtilAlarm
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "memory-util"
         metric: "MemoryUtilization"
         namespace: "Windows/Default"
         statistic: Minimum
         comparison: ">"
         threshold: 85
         period: 300
         evaluation_periods: 2
         unit: "Percent"
         description: "Alarm is triggered when the memory is full"
         dimensions: {'InstanceId': "i-04c62b676ca15122e" }
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     - name: DiskUtilAlarm
       ec2_metric_alarm:
         state: present
         region: us-west-2
         name: "disk-util"
         metric: "DiskSpaceUtilization"
         namespace: "Windows/Default"
         statistic: Minimum
         comparison: ">"
         threshold: 85
         period: 300
         evaluation_periods: 2
         unit: "Percent"
         description: "Alarm is triggered when the memory is full"
         dimensions: {'InstanceId': "i-04c62b676ca15122e"}
         alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
         
     
     
