- name: Creating CloudWatch Alarm for Windows instance
  hosts: all
  tasks:
    - name: Download required packages
      script: aws-cli.ps1
    - name: install the msi package
      win_msi:
        path: C:\awstemp\AWSCLI64.msi
        wait: true
      ignore_errors: yes
    - name: install python 
      raw: 'C:\awstemp\python-3.6.0.exe /quiet InstallAllUsers=1 PrependPath=1 Include_test=0'
    
