- name: Installing Boto
  hosts: all
  become: True
  gather_facts: False
  tasks:
     - name: Install python-pip
       yum: name=python-pip
       ignore_errors: yes
     - name: pip install boto
       pip: name=boto
       ignore_errors: yes
