- name: Linux MSP 
  hosts: all
  become: True
  #become_method: su
  #become_user: root
  gather_facts: False
  tasks:
     - name: Copy user-data
       template:
        src: user-data.sh
        dest: /home/ec2-user/user-data.sh
     - name: Setting Up Systemd for Amazon Linux
       shell: sudo yum-config-manager --enable epel
     - name: Setup cloudwatch logs
       shell: bash /home/ec2-user/user-data.sh
     - name: download ssm agent
       get_url: url="https://amazon-ssm-us-west-2.s3.amazonaws.com/latest/linux_amd64/amazon-ssm-agent.rpm" dest="/home/ec2-user/amazon-ssm-agent.rpm" mode=0755
     - name: sudo install ssm agent
       yum: name=/home/ec2-user/amazon-ssm-agent.rpm state=present
     - name: Start and Enable ssm agent
       service: name=amazon-ssm-agent state=started enabled=yes
- include: install-boto.yml
- include: cloudwatch-alarm.yml
