- name: create CloudWatch Alarms
  hosts: all
  become: True
  gather_facts: True
  tasks:
     - name: create alarm
       ec2_metric_alarm:
        state: present
        region: us-west-2
        name: "CPU-UTIL-Windows"
        metric: "CPUUtilization"
        namespace: "AWS/EC2"
        statistic: Average
        comparison: "<="
        threshold: 5.0
        period: 300
        evaluation_periods: 3
        unit: "Percent"
        description: "This will alarm when a bamboo slave's cpu usage average is lower than 5% for 15 minutes "
        dimensions: {'InstanceId':'i-0bb2b5eee26978bfb'}
        alarm_actions: ["arn:aws:sns:us-west-2:641434276274:Logging-rInstanceAlarmTopic-MINIPSHEPMCM"]
